/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.robles.pruebagui;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author santiagorobles
 */
public class ControlPanel extends javax.swing.JPanel {

    public double frequency1 = 840;
    public List<GuitarString> list1 = new ArrayList<>();

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfFrecuencia1 = new javax.swing.JTextField();
        bAdd = new javax.swing.JButton();
        lStatus = new javax.swing.JLabel();
        bReproduce = new javax.swing.JButton();
        bErase = new javax.swing.JButton();

        jLabel1.setText("Frequency");

        tfFrecuencia1.setColumns(7);
        tfFrecuencia1.setText("840");
        tfFrecuencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFrecuencia1ActionPerformed(evt);
            }
        });

        bAdd.setText("Add String");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        lStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lStatus.setText("Waiting...");

        bReproduce.setText("Reproduce");
        bReproduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReproduceActionPerformed(evt);
            }
        });

        bErase.setText("Erase Strings");
        bErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEraseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAdd)
                            .addComponent(jLabel1)
                            .addComponent(bReproduce)
                            .addComponent(bErase)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lStatus)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lStatus)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bReproduce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bErase)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfFrecuencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFrecuencia1ActionPerformed
        // TODO add your handling code here:
        String text = tfFrecuencia1.getText();
        try {
            frequency1 = Double.parseDouble(text);
        } catch (Exception e) {
            tfFrecuencia1.setText("880");
            frequency1 = 880;
        }
    }//GEN-LAST:event_tfFrecuencia1ActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        GuitarString string = new GuitarString(frequency1);
        list1.add(string);
        lStatus.setText("Added " + frequency1 + " Hz string");
    }//GEN-LAST:event_bAddActionPerformed

    private void bReproduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReproduceActionPerformed
        // TODO add your handling code here:
        String frequencies = "";
        for (GuitarString string : list1) {
            string.pluck();
            frequencies = frequencies.concat(string.toString() + " ");
        }
        frequencies = frequencies.trim();
        lStatus.setText("Produced frequencies: " + frequencies.replace(" ", ", "));
        for (int i = 0; i < 100_000; i++) {
            double finalSound = 0;
            for (GuitarString string : list1) {
                finalSound += string.sample();
            }
            StdAudio.play(finalSound);
            for (GuitarString string : list1) {
                string.tic();
            }
        }
    }//GEN-LAST:event_bReproduceActionPerformed

    private void bEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEraseActionPerformed
        // Erase array of Strings
        int listSize = list1.size();
        for(int i = 0; i < listSize ; i++){
            list1.remove(0);
        }
        lStatus.setText("Erased Strings");
        System.out.println(list1);
    }//GEN-LAST:event_bEraseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bErase;
    private javax.swing.JButton bReproduce;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lStatus;
    private javax.swing.JTextField tfFrecuencia1;
    // End of variables declaration//GEN-END:variables
}
