/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.robles.pruebagui;

/**
 *
 * @author santiagorobles
 */
public class ControlPanel extends javax.swing.JPanel {

    public double frequency1 = 840;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfFrecuencia1 = new javax.swing.JTextField();
        bSonar = new javax.swing.JButton();

        jLabel1.setText("Frecuencia 1");

        tfFrecuencia1.setColumns(7);
        tfFrecuencia1.setText("880");
        tfFrecuencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFrecuencia1ActionPerformed(evt);
            }
        });

        bSonar.setText("Sonar");
        bSonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSonarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bSonar))
                    .addComponent(jLabel1)
                    .addComponent(tfFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSonar)
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfFrecuencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFrecuencia1ActionPerformed
        // TODO add your handling code here:
        String text = tfFrecuencia1.getText();
        try {
            frequency1 = Double.parseDouble(text);
        } catch (Exception e) {
            tfFrecuencia1.setText("880");
        }
    }//GEN-LAST:event_tfFrecuencia1ActionPerformed

    private void bSonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSonarActionPerformed
        // TODO add your handling code here:
        GuitarString string = new GuitarString(frequency1);
        string.pluck();
        for (int i = 0; i < 100_000; i++) {
            StdAudio.play(string.sample());
            string.tic();
        }
    }//GEN-LAST:event_bSonarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSonar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfFrecuencia1;
    // End of variables declaration//GEN-END:variables
}
